
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OpenCV-ObjC' do
    #pod 'OpenCV', '~> 3.4.2'

end

target 'OpenCV-ObjCTests' do
    #pod 'OpenCV', '~> 3.4.2'
    
end
